# Generated by Django 5.2.7 on 2025-10-29 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='music_covers/'),
        ),
        migrations.AddField(
            model_name='music',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_music', to=settings.AUTH_USER_MODEL),
        ),
    ]
